SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE t_user ADD COLUMN if not EXISTS lon varchar(20), ADD COLUMN if not EXISTS lat varchar(20);
ALTER TABLE t_user MODIFY COLUMN lon VARCHAR(20) COMMENT '经度';
ALTER TABLE t_user MODIFY COLUMN lat VARCHAR(20) COMMENT '维度1111';

SET FOREIGN_KEY_CHECKS = 1;