/*
 * Power by www.xiaoi.com
 */
package com.eastrobot.heap.derby;

import java.io.File;
import java.sql.*;

/**
 * @author <a href="mailto:eko.z@outlook.com">eko.zhan</a>
 * @version 1.0
 * @date 2019/4/10 14:48
 */
public class DerbyUtils {

    private static final String JDBC_DRIVER_NAME = "org.apache.derby.jdbc.EmbeddedDriver";
    private static final String NACOS_HOME = "D:\\nacos";
    private static final String DERBY_BASE_DIR = "data" + File.separator + "derby-data";
    private static final String USER_NAME = "nacos";
    private static final String PASSWORD = "nacos";

    static Connection conn = null;

    public static Connection getConnection() {
        if (conn==null){
            try {
                Class.forName(JDBC_DRIVER_NAME);
                String url = "jdbc:derby:" + NACOS_HOME + File.separator + DERBY_BASE_DIR + ";create=true";
                conn = DriverManager.getConnection(url, USER_NAME, PASSWORD);
            } catch (ClassNotFoundException e) {
                e.printStackTrace();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        return conn;
    }

    public static void createTable(){
        getConnection();
        try {
            PreparedStatement pstmt = conn.prepareStatement("CREATE TABLE dev_user (" +
                    "id bigint NOT NULL generated by default as identity, " +
                    "name varchar(64), " +
                    "age int " +
                    ") ");
            pstmt.executeUpdate();
            conn.commit();
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }
}
