FROM elasticsearch:6.8.7

MAINTAINER eko.zhan

#es插件目录
ENV ES_PLUGINS_PATH /usr/share/elasticsearch/plugins

#定义存放ik分词器文件的目录
ENV ik_SRC_COMPILE_PATH /opt/ik_build

#创建存放ik分词器文件的目录
RUN mkdir $ik_SRC_COMPILE_PATH && \

#进入编译ik分词器文件的目录
cd $ik_SRC_COMPILE_PATH && \

#下载ik包
wget https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.8.7/elasticsearch-analysis-ik-6.8.7.zip && \

#解压zip包
unzip elasticsearch-analysis-ik-6.8.7 -d  analysis-ik&& \

#构建成功后，将文件移动到插件目录
mv analysis-ik $ES_PLUGINS_PATH/