version: '3'

services:
  mysql-1:
    # 指定容器的名称
    container_name: mysql-1
    # 指定镜像和版本
    image: mysql:8.0
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${GLOBAL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    restart: always
    volumes:
    # 挂载数据目录
    - "${GLOBAL_DIR}/data_mysql:/var/lib/mysql"
    # 挂载配置文件目录
  #      - "${GLOBAL_DIR}/config:/etc/mysql/conf.d"
  redis-1:
    container_name: redis-1
    image: redis:5.0.0
    command: redis-server --requirepass ${GLOBAL_PASSWORD}
    ports:
    - "6379:6379"
    restart: always
    volumes:
    - "${GLOBAL_DIR}/data_redis:/data"
