version: '3'

# docker-compose --env-file ../.env up -d
services:
  neo4j-1:
    container_name: neo4j-1
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/${GLOBAL_PASSWORD}
    restart: always
    volumes:
      # 挂载数据目录
      - "${GLOBAL_DIR}/data_neo4j/data:/data"
      - "${GLOBAL_DIR}/data_neo4j/logs:/logs"
      - "${GLOBAL_DIR}/data_neo4j/import:/var/lib/neo4j/import"
      - "${GLOBAL_DIR}/data_neo4j/plugins:/plugins"