version: '2'
services:
  neo4j-1:
    container_name: neo4j-1
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/neo4j88
    restart: always
    volumes:
      # 挂载数据目录
      - "D:/mnt/data/infra/data_neo4j/data:/data"
      - "D:/mnt/data/infra/data_neo4j/logs:/logs"
      - "D:/mnt/data/infra/data_neo4j/import:/var/lib/neo4j/import"
      - "D:/mnt/data/infra/data_neo4j/plugins:/plugins"